### PR TITLE
Remove storage of incidence data as parameters in malaria.py to reduce memory usage

### PR DESCRIPTION
**Pull request by joehcollins**
@tdm32 @tamuri - had some time to look at this and simply swapped out the use of self.parameters for a local variable in the function where this data is used as per Asif's suggestion. Malaria tests running fine for me locally. Let me know if theres other tweaks I can make to save Tara a job. 

This addresses #1538

### CODE REVIEW

**Comment by tamuri** [comment]
i think some other worksheets are also not used or needed. Now would be a good time to remove them too!

**Comment by joehcollins** [comment]
@tdm32 - not sure if i've helped or made more work this this but don't want to remove any files as per Asif's comment until you have reviewed.

Noted the failed test as `test_linear_model_for_clinical_malaria()` as its calling for one of the parameters that no longer exists.

**Comment by tdm32** [comment]
> i think some other worksheets are also not used or needed. Now would be a good time to remove them too!

Some of the worksheets are not used in the simulation but are used for plotting / calibration. I could try and combine them into fewer (but larger) worksheets?

**Comment by tdm32** [comment]
> @tdm32 - not sure if i've helped or made more work this this but don't want to remove any files as per Asif's comment until you have reviewed.
> 
> Noted the failed test as `test_linear_model_for_clinical_malaria()` as its calling for one of the parameters that no longer exists.
@joehcollins failing test is now fixed

**Review by tdm32 — APPROVED** [review]

**Comment by tdm32** [comment]
Thanks for this @joehcollins

**Comment by tamuri** [comment]
> Some of the worksheets are not used in the simulation but are used for plotting / calibration. I could try and combine them into fewer (but larger) worksheets?

**Comment by joehcollins** [comment]
perfect - thanks @tdm32!! @tamuri this should be ready for your review now

**Comment by tdm32** [comment]
> > Some of the worksheets are not used in the simulation but are used for plotting / calibration. I could try and combine them into fewer (but larger) worksheets?
> 
> Do you need to load them in the malaria module?

no - there are definitely a few there that aren't loaded

**Comment by tamuri** [comment]
Currently, only interested in those worksheets that are being unnecessarily loaded (or held during the simulation run) in parameters in the malaria module but not needed after read_parameters. Joe's PR deals with three of them but are there others?

For example, the line `p['interv'] = workbook['interventions']` - I don't see this dataframe being used anywhere in the malaria module. Can we remove it?

**Comment by tdm32** [comment]
> Currently, only interested in those worksheets that are being unnecessarily loaded (or held during the simulation run) in parameters in the malaria module but not needed after read_parameters. Joe's PR deals with three of them but are there others?
> 
> For example, the line `p['interv'] = workbook['interventions']` - I don't see this dataframe being used anywhere in the malaria module. Can we remove it?

Ok got it! Yes I've removed this now. The others that I was thinking of aren't loaded in the malaria module

**Pull request merged**
