### PR TITLE
Roll back PR #1027

### PR DESCRIPTION
**Pull request by tbhallett**

### CODE REVIEW

**Comment by tbhallett** [comment]
@marghe-molaro -- are we happy with this one going in now?

**Comment by marghe-molaro** [comment]
> @marghe-molaro -- are we happy with this one going in now?

@joehcollins, I think you are better suited to double checking this, as it was your PR that's being rolled back.

I can confirm that the combination of this PR with #1143 appears to solve issue #1102 as we were hoping.

**Comment by joehcollins** [comment]
@marghe-molaro @tbhallett yep this looks correct to me!

**Comment by tbhallett** [comment]
Thanks both. In that case, Please can you Approve this PR.

**Review by marghe-molaro — APPROVED** [review]

**Pull request merged**
