### PR TITLE
Label consumables as diagnostics/medicines/other and vital/essential/neither

### PR DESCRIPTION
**Pull request by tbhallett**
Here we introduce a method for labelling consumables items as either diagnostic, medicine, or other.

We also introduce new options for `availability` in the `Consumables` class that uses this information: 
*  'all_diagnostics_available'
* 'all_medicines_available'
* 'all_medicines_and_other_available'

Lastly, we update the way `availability` is updated mid-way through the simulation to use the `@property` syntax that used in `Equipment` and `Beddays`.

(p.s. @sakshimohan  -- you've already seen a preview of this in one of the scripting branches)

### CODE REVIEW

**Comment by tbhallett** [comment]
@tbhallett will add label of 'vital', provided by @sakshimohan

**Comment by sakshimohan** [comment]
> @tbhallett will add label of 'vital', provided by @sakshimohan

Thanks, Tim. Will send it over to you by this evening.

**Comment by sakshimohan** [comment]
Hi @tbhallett. Here is the list of TLO consumables along with their _Therapeutic priority code_ - (**V**ital or **E**ssential). This is taken from the Malawi Essential Medicines List in the [2015 Malawi Standard treatment guidelines](https://extranet.who.int/ncdccs/data/mwi_d1_malawi-standard-treatment-guidelines-essential-medicines-list-2015.pdf)
I've only managed to extract the Therapeutic priority code for 185 consumables in the model. 
[essential_medicine_list_categorisation.csv](https://github.com/UCL/TLOmodel/files/15394848/essential_medicine_list_categorisation.csv)

Unless we figure out a way to scrape the data in the Essential medicines list and then map it to the list of >2000 consumables in the RF you've created here, it would be challenging to take this further. However, if it's enough to just try to extract the _Therapeutic priority code_ of as many consumables in the list of ~220 consumables (as in the `ResourceFile_Costing.xlsx` file) which we know are currently used in the model, I could try to do this manually to get the number of consumables on which we have _Therapeutic priority code_ from 185 to ~220. 

 Screenshot 2024-05-21 at 20 53 42

Here is how I created the dataset (code below)- 
1. Manually extracted Essential Medicines List data for 143 consumables in the HHFA for my Lancet paper. This is in dropbox - `~/07 - Data/HHFA_2018-19/2 clean/essential_medicine_list_mapping.csv  ` 
2. Matched it to TLO item codes using the TLO model-HHFA crosswalk which was previously done. This is in `ResourceFile_consumables_matched.csv` in the repository. 
 
```
# Load Essential Medicines List Mapping data
essential_med_mapping =  pd.read_csv(path_to_dropbox / '07 - Data/HHFA_2018-19/2 clean/essential_medicine_list_mapping.csv')
essential_med_mapping = essential_med_mapping.rename(columns = {'Cleaned consumable name': 'item_hhfa'})

# Merge data with TLO consumables
consumable_crosswalk_df = pd.read_csv(path_for_new_resourcefiles / 'ResourceFile_consumables_matched.csv', encoding='ISO-8859-1')
consumable_crosswalk_df = consumable_crosswalk_df.drop_duplicates(['item_code', 'item_hhfa'])
tlo_essential_medicines = consumable_crosswalk_df[['item_code', 'consumable_name_tlo', 'item_hhfa']].merge(essential_med_mapping[['item_hhfa', 'Approved level of use', 'Therapeutic priority', 'Procurement system']],
                                                        left_on = ['item_hhfa'], right_on = ['item_hhfa'], how = 'left')

tlo_essential_medicines.to_csv(outputfilepath / 'essential_medicine_list_categorisation.csv', index = False)
```

**Comment by tbhallett** [comment]
Thanks ever so much for this, @sakshimohan

Before I digest it, I have a question:  When you say, "_Here_ is the list of TLO consumables along with their...." .... where should I find it? Did you possibly mean to push something to the branch or attach/link a file to that comment.  So sorry if I am misunderstanding!

**Comment by sakshimohan** [comment]
Does this link work for you?
[essential_medicine_list_categorisation.csv](https://github.com/UCL/TLOmodel/files/15394848/essential_medicine_list_categorisation.csv)

**Comment by tbhallett** [comment]
> Does this link work for you? [essential_medicine_list_categorisation.csv](https://github.com/UCL/TLOmodel/files/15394848/essential_medicine_list_categorisation.csv)

Yes - brilliant, thanks

**Comment by tbhallett** [comment]
I've used this snippet to create a flag for essential or vital items,. using the file linked-to [above](https://github.com/UCL/TLOmodel/pull/1351#issuecomment-2124150259) (now also in dropbox)


```python
from pathlib import Path
import pandas as pd

# Resource file as it stands currently (original designations were done "by hand")
filepath_original = Path('resources/healthsystem/consumables/ResourceFile_Consumables_Item_Designations.csv')

# File linked-to above
path_to_dropbox = Path('/Users/tbh03/SPH Imperial College Dropbox/Tim Hallett/Thanzi la Onse Theme 1 SHARE/')
f = pd.read_csv(path_to_dropbox / '07 - Data' / 'essential_medicine_list_categorisation.csv')

# Find the set of item_codes that are labelled essential or viral
essential_or_vital = set(f.loc[f['Therapeutic priority'].isin(['V', 'E']), 'item_code'].values)

# Add column in original_rf dataframe
original_rf = pd.read_csv(filepath_original)
original_rf['is_essential_or_vital'] = original_rf['Item_Code'].isin(essential_or_vital)

# Save the updated rf (over-writing the existing version)
original_rf.to_csv(filepath_original, index=False)
```

**Comment by sakshimohan** [comment]
Thanks, @tbhallett . Looks good. A couple of questions -
1. In the regression analysis, probability of availability was significantly associated with consumables being categorised as _Vital_ but not with consumables being categorised as _Essential_. So in the Lancet paper, the binary label is based on classification of drugs as 'V' alone and not 'V' or 'E'. Should we follow the same logic here or would you rather stick with `essential_or_vital`?
2. I know you've assumed that all among the 2016 consumables in `ResourceFile_Consumables_Item_Designations.csv` which are not in `essential_medicine_list_categorisation.csv` are not `essential_or_vital`. But this may not be the case because we just haven't looked up a majority of these consumables in the Essential Medicines List (because our search was limited to the 162 consumables in the HHFA). Is the expectation that we'll eventually complete this data?

**Comment by tbhallett** [comment]
> Thanks, @tbhallett . Looks good. A couple of questions -
> 
> 1. In the regression analysis, probability of availability was significantly associated with consumables being categorised as _Vital_ but not with consumables being categorised as _Essential_. So in the Lancet paper, the binary label is based on classification of drugs as 'V' alone and not 'V' or 'E'. Should we follow the same logic here or would you rather stick with `essential_or_vital`?

Good spot. Yes, we should follow the same logic here. I've add a column 'is_essential' with the code below, and will update the logic in the `Consumables` class to use the `is_essential` designation.

```python
from pathlib import Path
import pandas as pd

# Resource file as it stands currently (original designations were done "by hand")
filepath_original = Path('resources/healthsystem/consumables/ResourceFile_Consumables_Item_Designations.csv')

# File linked-to above
path_to_dropbox = Path('/Users/tbh03/SPH Imperial College Dropbox/Tim Hallett/Thanzi la Onse Theme 1 SHARE/')
f = pd.read_csv(path_to_dropbox / '07 - Data' / 'essential_medicine_list_categorisation.csv')

# Find the set of item_codes that are labelled essential or viral
essential = set(f.loc[f['Therapeutic priority'].isin(['E']), 'item_code'].values)
essential_or_vital = set(f.loc[f['Therapeutic priority'].isin(['V', 'E']), 'item_code'].values)

# Add column in original_rf dataframe
original_rf = pd.read_csv(filepath_original)
original_rf['is_essential'] = original_rf['Item_Code'].isin(essential)
original_rf['is_essential_or_vital'] = original_rf['Item_Code'].isin(essential_or_vital)

# Save the updated rf (over-writing the existing version)
original_rf.to_csv(filepath_original, index=False)
```

> 2. I know you've assumed that all among the 2016 consumables in `ResourceFile_Consumables_Item_Designations.csv` which are not in `essential_medicine_list_categorisation.csv` are not `essential_or_vital`. But this may not be the case because we just haven't looked up a majority of these consumables in the Essential Medicines List (because our search was limited to the 162 consumables in the HHFA). Is the expectation that we'll eventually complete this data?

I suppose so. But, I was perhaps (subconsciously!) assuming that the most essential items with have been in the HHFA (i.e. there would be few essential items not included in the HHFA, and so few missed by our categorisation). Is that a faulty assumption?

**Comment by tbhallett** [comment]
@tbhallett  --- got it wrong --- should have been V only for `is_vital` todo.

**Comment by tbhallett** [comment]
argh! 

Updated code snippet for generating the ResourceFile we need:

```
from pathlib import Path
import pandas as pd

# Resource file as it stands currently (original designations were done "by hand")
filepath_original = Path('resources/healthsystem/consumables/ResourceFile_Consumables_Item_Designations.csv')

# File linked-to above
path_to_dropbox = Path('/Users/tbh03/SPH Imperial College Dropbox/Tim Hallett/Thanzi la Onse Theme 1 SHARE/')
f = pd.read_csv(path_to_dropbox / '07 - Data' / 'essential_medicine_list_categorisation.csv')

# Find the set of item_codes that are labelled essential or viral
vital = set(f.loc[f['Therapeutic priority'].isin(['V']), 'item_code'].values)
essential_or_vital = set(f.loc[f['Therapeutic priority'].isin(['V', 'E']), 'item_code'].values)

# Add column in original_rf dataframe
original_rf = pd.read_csv(filepath_original)
original_rf['is_vital'] = original_rf['Item_Code'].isin(vital)
original_rf['is_essential_or_vital'] = original_rf['Item_Code'].isin(essential_or_vital)

# Save the updated rf (over-writing the existing version)
original_rf.to_csv(filepath_original, index=False)
```

**Comment by sakshimohan** [comment]
> argh!
> 
> Updated code snippet for generating the ResourceFile we need:
> 
> ```python
> from pathlib import Path
> import pandas as pd
> 
> # Resource file as it stands currently (original designations were done "by hand")
> filepath_original = Path('resources/healthsystem/consumables/ResourceFile_Consumables_Item_Designations.csv')
> 
> # File linked-to above
> path_to_dropbox = Path('/Users/tbh03/SPH Imperial College Dropbox/Tim Hallett/Thanzi la Onse Theme 1 SHARE/')
> f = pd.read_csv(path_to_dropbox / '07 - Data' / 'essential_medicine_list_categorisation.csv')
> 
> # Find the set of item_codes that are labelled essential or viral
> vital = set(f.loc[f['Therapeutic priority'].isin(['V']), 'item_code'].values)
> 
> # Add column in original_rf dataframe
> original_rf = pd.read_csv(filepath_original)
> original_rf['is_vital'] = original_rf['Item_Code'].isin(vital)
> 
> # Save the updated rf (over-writing the existing version)
> original_rf.to_csv(filepath_original, index=False)
> ```

Hi @tbhallett. I've now made the update we discussed during our morning call. This update adds the therapeutic code for consumables which were not in the HHFA (and therefore hadn't previously been looked up in the Essential Meds List). As a result, some consumables, mainly mental health, have been classified as vital. 

A final note that the `path_to_dropbox / '07 - Data' / 'essential_medicine_list_categorisation.csv'` file now contains an additional column `Type of consumable` which categorises consumables as either `drug or vaccine` or `other consumable`. None of the `other consumable` such as blood, oxygen, IV set are included in the Essential Medicine List so they will automatically be classified as NOT `Vital` in this analysis. I don't think we need to do anything about this but just bringing it to your attention.

**Review by sakshimohan — APPROVED** [review]

**Pull request merged**
