### PR TITLE
Remove usages of `[DataFrame|Series].append` methods in `contraception` module

### LINKED ISSUE #1113: Use of deprecated `DataFrame.append` / `Series.append` methods in `contraception` module
A couple of usages of `append` have slipped in (see #889 and #912) since we addressed previously

https://github.com/UCL/TLOmodel/blob/12f6cc5ec389257e60d4a2fde9afa77664baab0d/src/tlo/methods/contraception.py#L452

https://github.com/UCL/TLOmodel/blob/12f6cc5ec389257e60d4a2fde9afa77664baab0d/src/tlo/methods/contraception.py#L715-L716

### PR DESCRIPTION
**Pull request by matt-graham**
Fixes #1113

### CODE REVIEW

**Comment by tamuri** [comment]
Please liaise with @EvaJanouskova, because I think we have some contraception feature branches that'll need to be updated with these changes.

**Comment by EvaJanouskova** [comment]
@matt-graham, Does it mean that I need to change such also in the `fnc_analyse_contraception.py`?

Eg, line 570
```
            # Include the output summation for all time periods:
            co_output_use_modern_tp_df = \
                co_output_use_modern_tp_df \
                .append(sum_use_all_times(co_output_use_modern_tp_df, in_use_output))
```

**Comment by matt-graham** [comment]
> @matt-graham, Does it mean that I need to change such also in the `fnc_analyse_contraception.py`?
> 
> Eg, line 570
> 
> ```
>             # Include the output summation for all time periods:
>             co_output_use_modern_tp_df = \
>                 co_output_use_modern_tp_df \
>                 .append(sum_use_all_times(co_output_use_modern_tp_df, in_use_output))
> ```

Hi @EvaJanouskova. Yes any usages of `DataFrame.append` or `Series.append` will need to be changed as these methods have been deprecated and no longer exist in Pandas v2.0+. If you are joining two dataframes then generally `pandas.concat((dataframe_1, dataframe_2))` is a drop-in replacement for `dataframe_1.append(dataframe_2)`.

**Comment by EvaJanouskova** [comment]
> > @matt-graham, Does it mean that I need to change such also in the `fnc_analyse_contraception.py`?
> > Eg, line 570
> > ```
> >             # Include the output summation for all time periods:
> >             co_output_use_modern_tp_df = \
> >                 co_output_use_modern_tp_df \
> >                 .append(sum_use_all_times(co_output_use_modern_tp_df, in_use_output))
> > ```
> 
> Hi @EvaJanouskova. Yes any usages of `DataFrame.append` or `Series.append` will need to be changed as these methods have been deprecated and no longer exist in Pandas v2.0+. If you are joining two dataframes then generally `pandas.concat((dataframe_1, dataframe_2))` is a drop-in replacement for `dataframe_1.append(dataframe_2)`.

@matt-graham, How fast do you need me to resolve this? Or since it doesn't affect the functionality of the model, only the analysis scripts, is it ok if I get to it later?

**Comment by matt-graham** [comment]
> @matt-graham, How fast do you need me to resolve this? Or since it doesn't affect the functionality of the model, only the analysis scripts, is it ok if I get to it later?

No urgency from my side; as you say the additional usages of `append` should only affect analysis scripts and so not affect anyone not using these particular scripts, I think Asif tagged you more to make you aware the changes here will also need to be merged in to any branches you are working on which are making changes to the contraception module.

**Comment by matt-graham** [comment]
> ## Run of all tests on Python v3.11 with Pandas v2.0 failed ❌
> 🆔 [16916431850](https://github.com/UCL/TLOmodel/actions/runs/6232713595/job/16916431850) ⏲️ 658 minutes #️⃣ [12f6cc5](https://github.com/UCL/TLOmodel/commit/12f6cc5ec389257e60d4a2fde9afa77664baab0d)

Failure here was as tests ran on tip of `master` at time of comment rather than this branch tip due to #1119 - once that's fixed will need to re-run to see if tests do pass on Pandas v2.0 with these changes.

**Comment by matt-graham** [comment]
One test failure still when running with Pandas 2.0 / Python 3.11

```
____________ test_two_loggers_in_healthsystem[83563095832589325021] ____________
tests/test_healthsystem.py:841: in test_two_loggers_in_healthsystem
    assert summary_hsi_event['squeeze_factor'].apply(pd.Series) \
E   AssertionError: assert {('Dummy:HSI_Dummy', 2010): 113431310.40270479, ('Dummy:HSI_Dummy', 2011): 113431310.40270479, ('Inpatient_Care:Inpatient_Care', 2010): 0.0, ('Inpatient_Care:Inpatient_Care', 2011): 0.0} == {('Dummy:HSI_Dummy', 2010): 113431310.40270501, ('Dummy:HSI_Dummy', 2011): 113431310.40270501, ('Inpatient_Care:Inpatient_Care', 2010): 0.0, ('Inpatient_Care:Inpatient_Care', 2011): 0.0}
E     Common items:
E     {('Inpatient_Care:Inpatient_Care', 2010): 0.0,
E      ('Inpatient_Care:Inpatient_Care', 2011): 0.0}
E     Differing items:
E     {('Dummy:HSI_Dummy', 2010): 113431310.40270479} != {('Dummy:HSI_Dummy', 2010): 113431310.40270501}
E     {('Dummy:HSI_Dummy', 2011): 113431310.40270479} != {('Dummy:HSI_Dummy', 2011): 113431310.40270501}
E     Full diff:
E       {
E     -  ('Dummy:HSI_Dummy', 2010): 113431310.40270501,
E     ?                                            ^^^
E     +  ('Dummy:HSI_Dummy', 2010): 113431310.40270479,
E     ?                                            ^^^
E     -  ('Dummy:HSI_Dummy', 2011): 113431310.40270501,
E     ?                                            ^^^
E     +  ('Dummy:HSI_Dummy', 2011): 113431310.40270479,
E     ?                                            ^^^
E        ('Inpatient_Care:Inpatient_Care', 2010): 0.0,
E        ('Inpatient_Care:Inpatient_Care', 2011): 0.0,
E       }
```
Will investigate.

**Comment by matt-graham** [comment]
> One test failure still when running with Pandas 2.0 / Python 3.11
> 
> ```
> ____________ test_two_loggers_in_healthsystem[83563095832589325021] ____________
> tests/test_healthsystem.py:841: in test_two_loggers_in_healthsystem
>     assert summary_hsi_event['squeeze_factor'].apply(pd.Series) \
> E   AssertionError: assert {('Dummy:HSI_Dummy', 2010): 113431310.40270479, ('Dummy:HSI_Dummy', 2011): 113431310.40270479, ('Inpatient_Care:Inpatient_Care', 2010): 0.0, ('Inpatient_Care:Inpatient_Care', 2011): 0.0} == {('Dummy:HSI_Dummy', 2010): 113431310.40270501, ('Dummy:HSI_Dummy', 2011): 113431310.40270501, ('Inpatient_Care:Inpatient_Care', 2010): 0.0, ('Inpatient_Care:Inpatient_Care', 2011): 0.0}
> E     Common items:
> E     {('Inpatient_Care:Inpatient_Care', 2010): 0.0,
> E      ('Inpatient_Care:Inpatient_Care', 2011): 0.0}
> E     Differing items:
> E     {('Dummy:HSI_Dummy', 2010): 113431310.40270479} != {('Dummy:HSI_Dummy', 2010): 113431310.40270501}
> E     {('Dummy:HSI_Dummy', 2011): 113431310.40270479} != {('Dummy:HSI_Dummy', 2011): 113431310.40270501}
> E     Full diff:
> E       {
> E     -  ('Dummy:HSI_Dummy', 2010): 113431310.40270501,
> E     ?                                            ^^^
> E     +  ('Dummy:HSI_Dummy', 2010): 113431310.40270479,
> E     ?                                            ^^^
> E     -  ('Dummy:HSI_Dummy', 2011): 113431310.40270501,
> E     ?                                            ^^^
> E     +  ('Dummy:HSI_Dummy', 2011): 113431310.40270479,
> E     ?                                            ^^^
> E        ('Inpatient_Care:Inpatient_Care', 2010): 0.0,
> E        ('Inpatient_Care:Inpatient_Care', 2011): 0.0,
> E       }
> ```
> 
> Will investigate.

This error also occurs when running tests with Pandas 2.0 / Python 3.11 from current `master` so is not related to the changes in this PR it seems, so will raise as a new issue

**Review by tamuri — APPROVED** [review]

**Pull request merged**
