### PR TITLE
Initial Version of Scenario definition and other associated amendments needed for the "Horizontal vs Vertical"-type Analysis,

### PR DESCRIPTION
**Pull request by tbhallett**
Developments to enable next generation of analyses, wherein we modify sets of parameters representing "Health System Strengthening" interventions and "Expansion of Vertical Programs". This is needed for the FCDO/GF analysis and planned ROI of HSS.

Includes giving the ScenarioSwitcher the functionality to make changes midway through the simulation.

### CODE REVIEW

**Comment by tbhallett** [comment]
Hi @tdm32, @marghe-molaro and @sakshimohan 

Here's a first draft of the 'vertical vs horizontal' programs. @marghe-molaro is running in its current form on Azure, which will be a very useful "sanity check" for the health system strengthening interventions. 🤞

The main file is `scripts/comparison_of_horizontal_and_vertical_programs/scenario_comparison_of_horizontal_and_vertical_programs.py`.

@tdm32  -- you'll see some placeholders for putting in the changes for the HIV / TB and Malaria modules. Please could you propose a PR for merging into this branch that would make that work? 

We can then run the whole thing again, and mock-up some figures (drawing heavily on the designs for the overview paper).

**Review by marghe-molaro — APPROVED** [review]

**Comment by tbhallett** [comment]
### Initial figures:

Additional_DALYs_Averted_vs_Baseline_2020-2030
Additional_Deaths_Averted_vs_Baseline_2020-2030
All_Scenarios:_DALYs_2020-2030
Deaths_2020-2030


### Questions / To-dos

- [ ] Full package has less impact than  perfect healthcare seeking alone -- why? It should have at least the same impact, as the full package includes perfect healthcare seeking.
- [ ] Why is 'perfect clinical practice' having a 'negative' impact on health? Is it due to this being in Mode 2 and it causing a proliferation of appointments that overwhelm the system? [Try it in Mode 1 / Try it with much larger incrrease in HRH]
- [ ] The benefits of increased human resource for health seem small. Are they the same as that found originally by Margherita?
- [ ] Add in equipment scenario.

- [ ] Add in HIV/TB/Malaria scenarios

**Comment by marghe-molaro** [comment]
@tbhallett, we have now tracked down the origin of the discrepancy in the two batches of rescaled mode 2 runs (see Issue #1348), down to a merger of master into the branch in this commit https://github.com/UCL/TLOmodel/commit/d56042fb65a30e258e16d2bcf342bf933963e5bf

It would be good to double check whether this could have affected this PR/the results you have shared too.

**Comment by tbhallett** [comment]
Second run is: `horizontal_and_vertical_programs-2024-06-06T214004Z`

**Comment by tbhallett** [comment]
To-do's

- [ ] Re-run the 'perfect clinical practice' scenario now that #1400 has been merged (which reduces the excessive demand for appointments for TB)
- [ ] Add in equipment scenario.
- [ ] Add in actual/funded HR scenario
- [ ] Update consumables scenario to be related to the top 99% of clinics etc. (drawing from #1367)
- [ ] Add in HIV/TB/Malaria scenarios

**Comment by tbhallett** [comment]
now merging in :
* https://github.com/UCL/TLOmodel/pull/1377

**Comment by tbhallett** [comment]
First run of `src/scripts/comparison_of_horizontal_and_vertical_programs/scenario_vertical_programs_with_and_without_hss.py` is: htm_with_and_without_hss-2024-06-27T162216Z

**Pull request merged**
