### PR TITLE
Update consumables in cancer modules

### PR DESCRIPTION
**Pull request by tbhallett**
This brings some refactoring of the consumables of the cancer modules. It is an antecedent of #1298.

### CODE REVIEW

**Review by joehcollins — APPROVED** [review]
Look good - thanks Tim!!

**Comment by tbhallett** [comment]
> Look good - thanks Tim!!

Thanks Joe.

For the 'todos' in `cancer_consuambles.py` -- is there anything we can do with these now, or do we solve them in the #1298?

**Comment by joehcollins** [comment]
I would go with the latter in the interest of getting this PR in?

**Comment by EvaJanouskova** [comment]
> > Look good - thanks Tim!!
> 
> Thanks Joe.
> 
> For the 'todos' in `cancer_consuambles.py` -- is there anything we can do with these now, or do we solve them in the #1298?

Thanks Tim. I agree with Joe, I would leave it for #1298, but if you like to solve any, I think you may be able to resolve the `# TODO: replace with cystoscope` if you merge in also the commit from Sakshi `Add cystoscope, endoscope and prostate specific antigen test to consumable list` and do the corresponding changes in the code.

**Review by EvaJanouskova — COMMENTED** [review]
It looks good, except for a few equipment leftovers:

**Comment by tbhallett** [comment]
> > > Look good - thanks Tim!!
> > 
> > 
> > Thanks Joe.
> > For the 'todos' in `cancer_consuambles.py` -- is there anything we can do with these now, or do we solve them in the #1298?
> 
> Thanks Tim. I agree with Joe, I would leave it for #1298, but if you like to solve any, I think you may be able to resolve the `# TODO: replace with cystoscope` (I think multiple of such across the cancer modules) and `# TODO: replace with PSA test when added to cons list` if you merge in also the commit from Sakshi `Add cystoscope, endoscope and prostate specific antigen test to consumable list` and do the corresponding changes in the code.

OK, I'll flag those those to-dos will be done on #1298.
(Eva - not sure I know where that commit you refer to is....?)

**Comment by tbhallett** [comment]
> It looks good, except for a few equipment leftovers:

Thanks very much for those spots and suggested changes!! Don't know how those slipped in! All gone now, hopefully.

**Comment by EvaJanouskova** [comment]
> > > > Look good - thanks Tim!!
> > > 
> > > 
> > > Thanks Joe.
> > > For the 'todos' in `cancer_consuambles.py` -- is there anything we can do with these now, or do we solve them in the #1298?
> > 
> > 
> > Thanks Tim. I agree with Joe, I would leave it for #1298, but if you like to solve any, I think you may be able to resolve the `# TODO: replace with cystoscope` (I think multiple of such across the cancer modules) and `# TODO: replace with PSA test when added to cons list` if you merge in also the commit from Sakshi `Add cystoscope, endoscope and prostate specific antigen test to consumable list` and do the corresponding changes in the code.
> 
> OK, I'll flag those those to-dos will be done on #1298. (Eva - not sure I know where that commit you refer to is....?)

it's in #1298

**Comment by EvaJanouskova** [comment]
> > > > > Look good - thanks Tim!!
> > > > 
> > > > 
> > > > Thanks Joe.
> > > > For the 'todos' in `cancer_consuambles.py` -- is there anything we can do with these now, or do we solve them in the #1298?
> > > 
> > > 
> > > Thanks Tim. I agree with Joe, I would leave it for #1298, but if you like to solve any, I think you may be able to resolve the `# TODO: replace with cystoscope` (I think multiple of such across the cancer modules) and `# TODO: replace with PSA test when added to cons list` if you merge in also the commit from Sakshi `Add cystoscope, endoscope and prostate specific antigen test to consumable list` and do the corresponding changes in the code.
> > 
> > 
> > OK, I'll flag those those to-dos will be done on #1298. (Eva - not sure I know where that commit you refer to is....?)
> 
> it's in #1298, there are two commits from Sakshi: [4d8712f](https://github.com/UCL/TLOmodel/commit/4d8712f403e86fcbedd90f057f105bc109b6eefd) & [ff4d072](https://github.com/UCL/TLOmodel/commit/ff4d0729c2b47c7616a457ff88ec12a8db5ac127)

Apologies, wrong number, it is in #1341.

**Pull request merged**
