### PR TITLE
Update newborn HIV screening

### PR DESCRIPTION
**Pull request by joehcollins**
Small change to scheduling of HIV screening for newborns via the newborn_outcomes module so that only newborns of mothers diagnosed with HIV receive screening (previously all newborns were being screened)

### CODE REVIEW

**Comment by joehcollins** [comment]
@tdm32 wondering if i can close this old PR now?? Or is this something that still needs fixing

**Comment by tbhallett** [comment]
@joehcollins  --- are you still working on this> Not sure if this PR is still active and in the queue for merging or not.

**Comment by joehcollins** [comment]
@tbhallett actually not sure on this one - i think i commented for @tdm32 to have a look and see if she remembers what our plan was here!!

**Comment by tdm32** [comment]
The function decide_whether_hiv_test_for_infant in hiv.py checks this condition. As long as this is in your branches, this issue can be closed

**Comment by joehcollins** [comment]
Yep thats in my current branch. Closing now.

**Pull request closed without merging**
