### PR TITLE
Editing units of consumable required: Cancers modules

### PR DESCRIPTION
**Pull request by EvaJanouskova**

### CODE REVIEW

**Comment by EvaJanouskova** [comment]
@Sakshi, the 3 items you added to the script that creates `RF_Items_and_Pkgs` require the script to be re-run to be used properly.

**Comment by EvaJanouskova** [comment]
@andrew-phillips-1, @joehcollins, I've done some updates in the consumables, please check if you agree with the final version: https://docs.google.com/spreadsheets/d/1iaGiGcgGenGl8TSm31EGtxOvzfgTtVoZMvxxC8wUBmI/edit#gid=0 (especially I did added syringes, gauze, Lidocaine and gloves where I believe are needed.)

**Comment by joehcollins** [comment]
> @andrew-phillips-1, @joehcollins, I've done some updates in the consumables, please check if you agree with the final version: https://docs.google.com/spreadsheets/d/1iaGiGcgGenGl8TSm31EGtxOvzfgTtVoZMvxxC8wUBmI/edit#gid=0 (especially I did added syringes, gauze, Lidocaine and gloves where I believe are needed.) _Also see the comments with questions there, thanks!_

All looks good to me @EvaJanouskova - please see my comment r.e. essential consumables. Basically we've historically avoided making 'small' consumables essential for interventions to occur (e.g. cannulas, blood tubes, gloves, gauze) and tried to stick to medications/larger essential items.

**Comment by andrew-phillips-1** [comment]
Thanks for all the work on this @EvaJanouskova and @joehcollins  I'm happy with this.

**Comment by tbhallett** [comment]
> > @andrew-phillips-1, @joehcollins, I've done some updates in the consumables, please check if you agree with the final version: https://docs.google.com/spreadsheets/d/1iaGiGcgGenGl8TSm31EGtxOvzfgTtVoZMvxxC8wUBmI/edit#gid=0 (especially I did added syringes, gauze, Lidocaine and gloves where I believe are needed.) _Also see the comments with questions there, thanks!_
> 
> All looks good to me @EvaJanouskova - please see my comment r.e. essential consumables. Basically we've historically avoided making 'small' consumables essential for interventions to occur (e.g. cannulas, blood tubes, gloves, gauze) and tried to stick to medications/larger essential items.

Those little items can be listed as optional, if you want to include them

**Pull request merged**
