### PR TITLE
Updates/fixes to MNH modules following on from Joe's PhD

### PR DESCRIPTION
**Pull request by joehcollins**
This PR contains fixes/updates made across the suite of maternal/perinatal health models during the final stages of my PhD. This mainly includes fixes to small errors, updates to parameter values and updates to analysis scripts to run with new version of pandas. 

In addition, i have now removed all of the logic in the model which is internally related to the squeeze factor in keeping with Margherita's work. I have rerun my own calibration scripts and everything seems fine.

To do:

- [x] Remove squeeze factor logic
- [x] Re-run MNH calibration scenario with squeeze factor removed
- [x] Update MNH calibration script
- [x] ?Update analysis scripts to run with new version of pandas
- [x] Flake8
- [x] Fix failing HS test

### CODE REVIEW

**Comment by joehcollins** [comment]
Question - should this PR also remove all the parameters related to the use of squeeze factors in the MNH model. There not being used in the master branch currently but the parameters and calls to the logic remain. Might be easiest just to remove in this PR

**Comment by marghe-molaro** [comment]
Hi @joehcollins, could you directly me to which test is failing? I can't seem to be able to see it currently as they're still running

**Comment by joehcollins** [comment]
Thanks @marghe-molaro its `test_all_treatment_ids_defined_in_priority_policies`

**Comment by marghe-molaro** [comment]
Luckily that should be an extremely easy fix!!

It basically means that in reviewing your modules you have added a treatment_ID that is currently not listed in the priority policies. So it needs to be added to the resources/healthsystem/priority_policies/ResourceFile_PriorityRanking_ALLPOLICIES.xlsx file. It should tell you which one is missing, otherwise can you think of any edits to treatment_ID names that you've made in this PR?

**Comment by joehcollins** [comment]
> Luckily that should be an extremely easy fix!!
> 
> It basically means that in reviewing your modules you have added a treatment_ID that is currently not listed in the priority policies. So it needs to be added to the resources/healthsystem/priority_policies/ResourceFile_PriorityRanking_ALLPOLICIES.xlsx file. It should tell you which one is missing, otherwise can you think of any edits to treatment_ID names that you've made in this PR?

ok fab will do - will just wait for these tests to rerun and get back to you

**Comment by joehcollins** [comment]
@marghe-molaro - i do have a new treatment ID i forgot about. am i just adding a row to every sheet in that resource file for that new ID?

**Comment by marghe-molaro** [comment]
Hi @joehcollins, yes that's right, and add a relevant priority to them for each of the policies. If you have any doubt about which priority to assign them under a particular policy do reach out.

**Comment by joehcollins** [comment]
@marghe-molaro - adding in the missing treatment ID has fixed part of the error but the error still remains. Looks like its saying theres an additional treatment id that shouldnt be on the list? but that treatment ID is definitely used... You should be able to see on the error now

**Comment by marghe-molaro** [comment]
Hi @joehcollins, did you change the way in which the treatment_ID DeliveryCare_Comprehensive is set by any chance? It could be that it is now no longer picked up by the function during the cold read of the code

**Comment by joehcollins** [comment]
> Hi @joehcollins, did you change the way in which the treatment_ID DeliveryCare_Comprehensive is set by any chance? It could be that it is now no longer picked up by the function during the cold read of the code

```
def __init__(self, module, person_id, timing, facility_level_of_this_hsi):
        super().__init__(module, person_id=person_id)
        assert isinstance(module, Labour)
       
        if timing == 'intrapartum':
            t_id = 'DeliveryCare_Comprehensive'
        else:
            t_id = 'PostnatalCare_Comprehensive'
        
        self.TREATMENT_ID = t_id
        self.EXPECTED_APPT_FOOTPRINT = self.make_appt_footprint({'MajorSurg': 1})
        self.ACCEPTED_FACILITY_LEVEL = facility_level_of_this_hsi
        self.timing = timing

```
Yep - this is now how the treatment ID is set up so thats likely related to the issue you describe above?

**Comment by joehcollins** [comment]
ahhh yes did see that for those - ok let me implement and then we should be all done!!

**Comment by tbhallett** [comment]
Adding @marghe-molaro to review for this, given the updating of the squeeze_factor logic.

**Review by tbhallett — APPROVED** [review]

**Comment by tbhallett** [comment]
Thanks @joehcollins 

As far as I can tell (which isn't that far!), this all seems fine and it's got that you've abscised the `squeeze_factor` logic. 

I think we should expedite putting this into `master` if this if the version that you're using for papers and things.

**Review by tamuri — APPROVED** [review]
Happy for you to merge

**Pull request merged**
