### PR TITLE
The Impact of Past Improvements in HRH: The Historical Analysis

### PR DESCRIPTION
**Pull request by tbhallett**
This PR does the analysis to estimate the impact of health of the increases in Human Resources for Health (healthcare workers) have occurred already in Malawi.

Dominic Nkhoma has provided data on the number of staff (4th July 2024), saved in the team Dropbox.

Basic descriptions of these data are shown below (done in the script `src/scripts/data_file_processing/healthsystem/human_resources/analysis_historic_changes_in_hr.py`)

image

image

### CODE REVIEW

**Comment by BinglingICL** [comment]
Nice trend before 2021. But big drops from 2021 to 2023, overall and consistently across all districts (except Likoma seemly). Was it because Covid-19 relevant or funds declined?

**Comment by tbhallett** [comment]
> Nice trend before 2021. But big drops from 2021 to 2023, overall and consistently across all districts (except Likoma seemly). Was it because Covid-19 relevant or funds declined?

I asked Dominic and he replies,
"""Dear Tim
The 2023 figures are wrong. I will investigate, for now please exclude 2023. Otherwise the rest looks good. 
 
regards
 
Dominic
"""

So I'll do that for now.

**Comment by tbhallett** [comment]
Construction of scenarios

image

**Comment by tbhallett** [comment]
First run of  `src/scripts/impact_of_historical_changes_in_hr/scenario_historical_changes_in_hr.py`

`historical_changes_in_hr-2024-07-08T145329Z`

**Comment by tbhallett** [comment]
So, the analysis and plotting script basically work and give some sensible-seeming results.

Things to do following discussion with team:

- [ ] Improve plotting: Show breakdown by cause of deaths/dalys; 
- [ ] Assemble summary slide deck
- [ ] Look at squeeze-factor over time in calibration plots (from Mode 1): Does it show a trend over time consistent with there being more HCW available (i.e., does the squeeze reduce over time)
- [ ] Test whether adjustment to the scaling calculation [to take account of the effect that we might be over-correcting?] make a difference to the 'delta' between the scenarios.

**Comment by tbhallett** [comment]
START AGAIN -- new data file provided, showing more modest changes. Will re-do analysis,
image

image
image

**Comment by tbhallett** [comment]
new figures for new scenarios

image

image

**Comment by tbhallett** [comment]
With new email from Dominic, giving final scale-up pattern.... new graphs below and job-id is:

image
image

image

**Comment by BinglingICL** [comment]
> With new email from Dominic, giving final scale-up pattern.... new graphs below and job-id is:
> 
> FULL-SIZE RUN: `historical_changes_in_hr-2024-08-14T090007Z`
> 
> MINI-RUN (BACKUP): `historical_changes_in_hr-2024-08-14T174730Z`
> 
> RUN (pop 20_000, EHPIII and max hcs & hs func, to take advantage of incr resources): `historical_changes_in_hr-2024-08-15T094244Z`
> 
> image image image

Thanks for keep sharing the latest results. It interests me a lot as I see the hcw staff count decreased a little bit but not much in the year of 2020, when the pandemic happened. And then from 2021, the hcw staff continue to expand, which shows some resilience of the healthcare system I would suppose.

**Comment by BinglingICL** [comment]
> > Thanks for keep sharing the latest results. It interests me a lot as I see the hcw staff count decreased a little bit but not much in the year of 2020, when the pandemic happened. And then from 2021, the hcw staff continue to expand, which shows some resilience of the healthcare system I would suppose.
> 
> Thanks: yes, maybe that is a part of it. I think it also shows the reforms that have been in put place starting to have an impact.

Thanks Tim. Is that a reform about hcw recruitment? By the way, may I know how long does it take to run this scenario?

**Comment by BinglingICL** [comment]
> > > Thanks for keep sharing the latest results. It interests me a lot as I see the hcw staff count decreased a little bit but not much in the year of 2020, when the pandemic happened. And then from 2021, the hcw staff continue to expand, which shows some resilience of the healthcare system I would suppose.
> > 
> > 
> > Thanks: yes, maybe that is a part of it. I think it also shows the reforms that have been in put place starting to have an impact.
> 
> Thanks Tim. Is that a reform about hcw recruitment? By the way, may I know how long does it take to run this scenario?

And Tim, I wonder if Dominic also has these years' hcw staff per cadre, especially for Clinical, DCSA, Nursing_and_Midwifery, and Pharmacy?

**Comment by tbhallett** [comment]
(Noting here that the version of the analysis provided externally is tagged here: https://github.com/UCL/TLOmodel/releases/tag/historical_hrh_analysis_v0.1)

**Comment by tbhallett** [comment]
@BinglingICL  -- please review and approve this one, so that we can have it in master to build-up with our PR #1534

**Review by tdm32 — APPROVED** [review]

**Comment by BinglingICL** [comment]
> @BinglingICL -- please review and approve this one, so that we can have it in master to build-up with our PR #1534

Sorry for not reviewing this PR in time. Grateful that Tara has approved it!

**Comment by BinglingICL** [comment]
> > @BinglingICL -- please review and approve this one, so that we can have it in master to build-up with our PR #1534
> 
> Sorry for not reviewing this PR in time. Grateful that Tara has approved it!

Hi Tim, although too late, but want to let you know that  I just had a run of the script to check how the yearly scale up factors derived. It look great to me!

And a note to me myself is that the overall increase rate of HRH from 2020 to 2024 is 38.017%.(@sakshimohan might be also interested in this as I remember in a previous meeting?)

**Pull request merged**
