### PR TITLE
omnibus comment changes

### PR DESCRIPTION
**Pull request by EvaJanouskova**
Fixed a few typos I came across.

Updated/moved some comments.

### CODE REVIEW

**Comment by tbhallett** [comment]
Thanks for this @EvaJanouskova  -- I'll leave this open a little longer in case other small things need to be changed.

**Comment by tbhallett** [comment]
> @tbhallett, The description at the top of `hsi_generic_first_appts.py` seems outdated, doesn't it?

Yes it is a bit, you’re right. It should explain that those appointments can run at different levels.

**Comment by tbhallett** [comment]
thanks for all these @EvaJanouskova --- is it ready to go in?

**Comment by EvaJanouskova** [comment]
> thanks for all these @EvaJanouskova --- is it ready to go in?

There will always be smt, but it is all I have right now, so I think it can go in.

**Review by tbhallett — APPROVED** [review]

**Pull request merged**
