### PR TITLE
tidy consumables resouce files

### PR DESCRIPTION
**Pull request by tbhallett**
This PR tidies up some old files to do with Consumables.  

I also investigated some issues as I was doing this and have the following observation and suggest Action points.

* As noted by @EvaJanouskova and @joehcollins , whereas the `item_code = 280` is defined as  "Diazepam 5mg_1000_CMST" (per `resources/healthsystem/consumables/ResourceFile_Consumables_Items_and_Packages.csv`), there is an entry in the file `resources/healthsystem/consumables/ResourceFile_consumables_matched.csv` that associates this `item_code` with "Endoscope" (line: 464). This seems not to cause any problem except confusion (the same file says there is no match for Endoscope). The question is: why does that file seem to say that 'Endoscope' has that item_code? I don't think there is any action to take here.

* The script `scripts/data_file_processing/healthsystem/consumables/consumable_resource_analyses_with_lmis/consumables_availability_estimation.py`  (which generates `ResourceFile_Consumables_availability_and_usage.csv` and `ResourceFile_Consumables_availability_small.csv`) does not run all the way through: for me, it hangs on line 281. (This is a step where some items are being renamed). 

- [x] **_Action_**: Make `consumables_availability_estimation.py` run all the way through

* I wanted to use the file to re-generate our definitions of `item_code` and 'pkg_code` using `scripts/data_file_processing/healthsystem/consumables/processing_data_from_one_health/generate_consumables_item_codes_and_packages.py`. This _almost_ works but the following are the differences between the file that exists currently in `master` and the file that is generated by running this script. (Comparison workbook here).
[Comparison workbook here](https://github.com/UCL/TLOmodel/files/14186076/comparison.of.item.defn.xlsx)

   * There is one more 'Package' defined: `Contraception initiation (Pkg_Code 164)`:  (This contains 1 Pregnancy Slide Test Kit (item 2019)). (Line 1782 gives: 
```python

{
    Intervention_Cat: Maternal/Newborn and Reproductive Health
    Intervention_Pkg: Contraception initiation
    Intervention_Pkg_Code: 164	
    Items: Pregnancy Slide Test Kit (Human - Chorionic Gonadotrophin (Hcg))_100_MM192300_CMST, strip
    Item_Code: 2019
    Item_Code_Avail: 2019
    Expected_Units_Per_Case: 1
    Unit_Cost: 32.164
    Source_Cost_Item: Malawi EHP 2021	
    Source_ExpectedUnits: Malawi EHP 2021
}
```
- [X] ~**_Action_**:  Decide if this definition should be added manually, as other _post hoc_ additions are in `generate_consumables_item_codes_and_packages.py`.~  Will be done in Issue #1274 

   * The name of some items have been modified in (seemingly) minor ways: 
   
image

I'm not sure if these changes are necessary or consequential or why they changed. It seems like #807 and #861 brought these changes.
- [X] **_Action_**:  Understand if these changes are to be kept (and so made reproducible in by inserting into the scripts) or not. (and Issue #1274)

* There is an additional column:
     * `Item_Code_Avail` which is mostly blank: I am not sure what this does
     * `Source_Cost_Item`
     * `Source_ExpectedUnits`

- [X] ~**_Action_**:  Understand if these changes are to be kept (and so made reproducible in by inserting into the scripts) or not.~ Will be done in (and Issue #1274)

### CODE REVIEW

**Comment by sakshimohan** [comment]
HI @tbhallett. Thank you so much for the detailed comments. Line 281 `lmis_df_wide_flat = rename_items_to_address_inconsistentencies(lmis_df_wide_flat, inconsistent_item_names_mapping)` runs for me but it took over an hour to complete. It's because of the way in which I've tried to collapse the data  - I think I can make this quicker. But I now get an error on line 379 (a reshape command) which is strange. I'll look at this and the rest of your comments more closely tomorrow.

**Comment by tbhallett** [comment]
> HI @tbhallett. Thank you so much for the detailed comments. Line 281 `lmis_df_wide_flat = rename_items_to_address_inconsistentencies(lmis_df_wide_flat, inconsistent_item_names_mapping)` runs for me but it took over an hour to complete. It's because of the way in which I've tried to collapse the data - I think I can make this quicker. But I now get an error on line 379 (a reshape command) which is strange. I'll look at this and the rest of your comments more closely tomorrow.

Thanks for looking into this @sakshimohan 

* It's good that it runs on  your machine. For me, it does crash. I think this is likely to be a pandas 2.0 upgrade thing. As long, as it's reproducible under a version of pandas it's OK. (And you don't need to spent time trying to speed it up!)
* On the other points - it's up for debate really; Let's see what @EvaJanouskova  and @joehcollins think.

**Comment by tbhallett** [comment]
That would be ok with me. 

If we all agree that we're happy with the current state and the write up above, then we can just merge these changes... And log as an issue.

**Comment by joehcollins** [comment]
Ok great- on reflection this was not a very helpful comment from me (above). I meant to say that i'm happy to spend more time on this to check everything if you'd find helpful as off the top of my head i'm not fully versed in how the spreadsheets are generated. 

The only other thing was that i think we discussed having endoscope as a consumable and use the availablity in the availability spreadsheet - does that still need doing?

**Review by joehcollins — APPROVED** [review]

**Comment by EvaJanouskova** [comment]
> The name of some items have been modified in (seemingly) minor ways:
image
I'm not sure if these changes are necessary or consequential or why they changed. It seems like https://github.com/UCL/TLOmodel/pull/807 and https://github.com/UCL/TLOmodel/pull/861 brought these changes.
>
> Action: Understand if these changes are to be kept (and so made reproducible in by inserting into the scripts) or not.

These are other changes I made manually in the `ResourceFile_Consumables_Items_and_Packages.csv`, I've changed some names according what we wanted to use with the contraception module and also 2 new items were added to be used with contraception module. I'm happy to discuss what to do about them.

**Comment by EvaJanouskova** [comment]
> There is an additional column:
Item_Code_Avail which is mostly blank: I am not sure what this does
Source_Cost_Item
Source_ExpectedUnits
 Action: Understand if these changes are to be kept (and so made reproducible in by inserting into the scripts) or not.

These changes came from the #876, where the columns are described:
"The `Item_Code` for every item used with contraceptive methods is matched with the item code of an item with the most similar name (`Item` in  _RF_Consumables_ ). However for the simulation purposes of default availability, a new column `Item_Code_Avail` is added. If the item code is in the availability data (_ResourceFile_Consumables_availability_small.csv_), `Item_Code_Avail` is the same as `Item_Code`, if it's not in the availability data the closest match (if any) of items included in availability data is written as `Item_Code_Avail` to be used to approximate the availability for the simulations with default availability.

I also added `Source_Cost_Item` (for all contraceptive items and their cost it is Malawi EHP 2021) & `Source_ExpectedUnits` (for items included in OHT 2016, those were used, the rest is based on Malawi EHP 2021) columns so it is easy to figure out which year the data are from in future and so it's clear which data were updated, hence does not come from the same source as the rest in the file."

If I remember correctly, @sakshimohan introduced automatic availability approximation, is that correct? If so (can I see where this is happening?), then the `Item_Code_Avail` column should not be needed anymore. However, both `Source_` columns would be good to preserve as when I got to the RF it took a long time to figure out where the data came from. It would be nice if whoever works with it in the future doesn't have to go through this again.

**Comment by EvaJanouskova** [comment]
@sakshimohan, and/or @tbhallett  Just out of curiosity, what is current use of `ResourceFile_Consumables_availability_and_usage.csv`?

**Comment by sakshimohan** [comment]
Hi @tbhallett. I have now been able to get the `consumables_availability_estimation.py` file run through to generate the two availability resource files. It seems like not having three ''' around one of the drug names which was being changes to deal with consumable names change in September in OpenLMIS was causing part of the issue. 

The dataframe collapse functions (`rename_items_to_address_inconsistentencies` and `collapse_stockout_data`) are taking really long to run now, perhaps because of the new version of pandas but they do complete on my computer after approx. 30-40 minutes. I have made a slight update to get the first one to run faster by only running on the part of the dataset which consists of inconsistent drug names over the course of 2018, rather than running it on the entire dataset as done previously. 

The resource files have not changed except some very negligible changes (very close to 0%) as shown in the screenshot below - 
Screenshot 2024-02-09 at 18 36 51

**Comment by sakshimohan** [comment]
> @sakshimohan, and/or @tbhallett Just out of curiosity, what is the current use of `ResourceFile_Consumables_availability_and_usage.csv`?

Hi @EvaJanouskova. We're not using this file currently but we had generated it previously to have a more detailed record of the amount of consumables received, stocked, dispensed each month (a more detailed version of `ResourceFile_Consumables_availability_small.csv`). We had previously considered doing the econometric analysis on factors associated with consumable availability on this LMIS dataset but decided to go with HHFA in the end for a few reasons. 

The file is 117MB so I'm not opposed to deleting it since we're not currently using it. @tbhallett if you agree, I can remove the line in `consumables_availability_estimation.py` which saves this resourcefile and delete the file.

**Review by sakshimohan — APPROVED** [review]

**Comment by tbhallett** [comment]
> Hi @tbhallett. I have now been able to get the `consumables_availability_estimation.py` file run through to generate the two availability resource files. It seems like not having three ''' around one of the drug names which was being changes to deal with consumable names change in September in OpenLMIS was causing part of the issue.
> 
> The dataframe collapse functions (`rename_items_to_address_inconsistentencies` and `collapse_stockout_data`) are taking really long to run now, perhaps because of the new version of pandas but they do complete on my computer after approx. 30-40 minutes. I have made a slight update to get the first one to run faster by only running on the part of the dataset which consists of inconsistent drug names over the course of 2018, rather than running it on the entire dataset as done previously.
> 
> The resource files have not changed except some very negligible changes (very close to 0%) as shown in the screenshot below - Screenshot 2024-02-09 at 18 36 51

Thanks very much for all this, @sakshimohan 

It's really great that you've got that script working, and very nice to know that we can reproduce that ResourceFile exactly.


One thing I spotted in your screenshot (and happens on my machine too) is that line 245488 has a Facility_ID value of ">107". i.e. not an integer.  I don't know how this happened --- but it could some markup from a git compare compare that crept in, as this is also a line with one of those small departures. I think this is the cause of the failing tests, so I'm putting in a manual correction to remove it.

**Comment by tbhallett** [comment]
> > @sakshimohan, and/or @tbhallett Just out of curiosity, what is the current use of `ResourceFile_Consumables_availability_and_usage.csv`?
> 
> Hi @EvaJanouskova. We're not using this file currently but we had generated it previously to have a more detailed record of the amount of consumables received, stocked, dispensed each month (a more detailed version of `ResourceFile_Consumables_availability_small.csv`). We had previously considered doing the econometric analysis on factors associated with consumable availability on this LMIS dataset but decided to go with HHFA in the end for a few reasons.
> 
> One reason I envision, we might end up using this data is some way is that the way in which we have characterised consumable availability is a fixed probability. This doesn't really allow us to explore what happens at the facility level if the central vendor simply purchases more consumables. This data might give us some insight into this because it records how probability of availability is associated with quantity received per month.
> 
> The file is 117MB so I'm not opposed to deleting it since we're not currently using it. @tbhallett if you agree, I can remove the line in `consumables_availability_estimation.py` which saves this resourcefile and delete the file.

Good points. I think it'd be nice to use such a file to examine actual usage of consumables (implied in this file) with what the model says. But, it's true that we don't use it now..... so, in the interests of being clear about our intentions, I would vote for:

* Deleting the file from the repo
* Commenting-out the line in the script that generates it
* Adding a comment at that point about this discussion!

**Comment by tbhallett** [comment]
@EvaJanouskova  -- to your comments

Sorry for my poor communication on this point. Indeed, we had not said anywhere properly that we wanted to be able to regenerate that file using the script  and, of course, we approved your PRs, so it shows I forgot too!

I think it's very debatable whether we want to preserve that `generate_consumables_item_codes_and_packages.py` generates `ResourceFile_Consumables_Items_and_Packages.csv`, .....

but, on balance, maybe we should do it whilst we're here and I agree with you, Eva, that we don't want to loose the work you did on the renaming/matching and also don't want someone to have re-do it because we can't see what was done / how it was done.

So, can I leave it with you, Eva, to raise an issue that says: Guarantee that `ResourceFile_Consumables_Items_and_Packages.csv` is perfectly regenerated by running `generate_consumables_item_codes_and_packages.py`.... and make the changes to the script accordingly?

It doesn't have to be your priority and this PR can go ahead in its current state.

**Comment by EvaJanouskova** [comment]
> > @sakshimohan, and/or @tbhallett Just out of curiosity, what is the current use of `ResourceFile_Consumables_availability_and_usage.csv`?
> 
> Hi @EvaJanouskova. 
> ....
> The file is 117MB so I'm not opposed to deleting it since we're not currently using it. @tbhallett if you agree, I can remove the line in `consumables_availability_estimation.py` which saves this resourcefile and delete the file. 

If the data in the file are not outdated, I would keep this file as there are some consumables we might want to add to the `ResourceFile_Consumables_Items_and_Packages.csv` in future, and it would be good to know that we have some availability data for them. I @joehcollins found there some he would like to be used.

**Comment by EvaJanouskova** [comment]
>  @EvaJanouskova  -- to your comments
> ....
> So, can I leave it with you, Eva, to raise an issue that says: Guarantee that `ResourceFile_Consumables_Items_and_Packages.csv` is perfectly regenerated by running `generate_consumables_item_codes_and_packages.py`.... and make the changes to the script accordingly?
> 
> It doesn't have to be your priority and this PR can go ahead in its current state.

Issue opened: [#1274](https://github.com/UCL/TLOmodel/issues/1274)

**Comment by joehcollins** [comment]
@sakshimohan can I just check then which resource file actually shows the availability values used within the model? I had previously thought this was `ResourceFile_Consumables_availability_and_usage.csv`?

**Comment by sakshimohan** [comment]
> @sakshimohan can I just check then which resource file actually shows the availability values used within the model? I had previously thought this was `ResourceFile_Consumables_availability_and_usage.csv`?

Hi @joehcollins. The model uses `ResourceFile_Consumables_availability_small.csv`. See line 804-808 of the [health system.py](https://github.com/UCL/TLOmodel/blob/master/src/tlo/methods/healthsystem.py). This is the file with cleaned district names and ensured that any missing data is interpolated. If there are consumables that you're using which aren't in  `ResourceFile_Consumables_availability_small.csv` but are in  `ResourceFile_Consumables_availability_and_usage.csv`, I can look into this an make a correction.

**Pull request merged**
