### PR TITLE
Update contributors

### PR DESCRIPTION
**Pull request by tbhallett**
Adding Gerald, Dominic, Victor and Rachel

### CODE REVIEW

**Review by RachelMurray-Watson — APPROVED** [review]
Looks good for me

**Comment by tbhallett** [comment]
@tamuri -- please could you regenerate the website and merge this, if you're happy with it?

**Comment by tamuri** [comment]
Will do.

**Comment by tbhallett** [comment]
Thanks. I can see that the checks are failing due to CITATION.CFF not being updated. And that this should be updated by running `python src/scripts/automation/update_citation.py`, but doing so, even though no errors raised, does not seem to touch the CITATION.CFF file.

**Comment by tamuri** [comment]
Yup, I see that - will fix

**Comment by tbhallett** [comment]
Thanks @tamuri 

This has had an unintended consequence of removing Sakshi from the software contributors. This arose because I wanted her to be listed under Health-Economics on the webpage, which I could only achieve by removing her other 'contribution' tags. 

Shall I roll back that change for Sakshi? (it being more important to have the citation file include her, than to worry about placements on the website). Or, is there a way to achieve both (keep her include in the citation.cff file, and make her be listed under 'Health Economics' on the webpage)?

**Comment by tamuri** [comment]
I'm checking, but I think it's just a matter of listing "Health economics" first, then "Software development"

**Comment by tbhallett** [comment]
Thanks so much @tamuri

**Pull request merged**
